os: linux
dist: bionic
language: c
arch:
  - amd64
  - arm64
  - ppc64le

addons:
  apt:
    packages:
      - valgrind
      - python3-pytest
      - python3-pytest-xdist
      - meson
      - ninja-build
      - pkg-config
      - libaio-dev
      - libblkid-dev
      - libkeyutils-dev
      - liblz4-dev
      - libscrypt-dev
      - libsodium-dev
      - liburcu-dev
      - libzstd-dev
      - uuid-dev
      - zlib1g-dev

before_install:
  - wget https://github.com/libfuse/libfuse/archive/fuse-3.7.0.tar.gz -O /tmp/fuse.tar.gz
  - tar -C /tmp -zxvf /tmp/fuse.tar.gz
  - mkdir /tmp/libfuse-fuse-3.7.0/build
  - pushd /tmp/libfuse-fuse-3.7.0/build && meson .. && ninja && sudo ninja install && popd
  - sudo ldconfig
  - ulimit -a
  - env
  - df -h
  - free
  - sysctl kernel.threads-max
  - sudo blockdev --report

before_script:
  - ulimit -c unlimited -S
  - sudo sysctl -w kernel.core_pattern="/tmp/core.%p"

script: ./smoke_test

after_failure:
  - find /tmp -name '*core*' -print
  - COREFILE=$(find /tmp -maxdepth 1 -name "core*" | head -n 1) # find core file
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" bcachefs -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
